## dev database
version: "3.9"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=dev
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
